package com.model.generate;

import java.util.Date;

public class LogInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.id
     *
     * @mbggenerated Mon Jan 13 16:46:43 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.action_param
     *
     * @mbggenerated Mon Jan 13 16:46:43 CST 2020
     */
    private String actionParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.createdate
     *
     * @mbggenerated Mon Jan 13 16:46:43 CST 2020
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.id
     *
     * @return the value of log_info.id
     *
     * @mbggenerated Mon Jan 13 16:46:43 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.id
     *
     * @param id the value for log_info.id
     *
     * @mbggenerated Mon Jan 13 16:46:43 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.action_param
     *
     * @return the value of log_info.action_param
     *
     * @mbggenerated Mon Jan 13 16:46:43 CST 2020
     */
    public String getActionParam() {
        return actionParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.action_param
     *
     * @param actionParam the value for log_info.action_param
     *
     * @mbggenerated Mon Jan 13 16:46:43 CST 2020
     */
    public void setActionParam(String actionParam) {
        this.actionParam = actionParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_info.createdate
     *
     * @return the value of log_info.createdate
     *
     * @mbggenerated Mon Jan 13 16:46:43 CST 2020
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_info.createdate
     *
     * @param createdate the value for log_info.createdate
     *
     * @mbggenerated Mon Jan 13 16:46:43 CST 2020
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}