package com.model.generate;

import java.util.Date;

public class Orderinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.id
     *
     * @mbggenerated Fri Jan 10 13:46:49 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.userId
     *
     * @mbggenerated Fri Jan 10 13:46:49 CST 2020
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.productId
     *
     * @mbggenerated Fri Jan 10 13:46:49 CST 2020
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.createDate
     *
     * @mbggenerated Fri Jan 10 13:46:49 CST 2020
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.status
     *
     * @mbggenerated Fri Jan 10 13:46:49 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.id
     *
     * @return the value of orderinfo.id
     *
     * @mbggenerated Fri Jan 10 13:46:49 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.id
     *
     * @param id the value for orderinfo.id
     *
     * @mbggenerated Fri Jan 10 13:46:49 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.userId
     *
     * @return the value of orderinfo.userId
     *
     * @mbggenerated Fri Jan 10 13:46:49 CST 2020
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.userId
     *
     * @param userid the value for orderinfo.userId
     *
     * @mbggenerated Fri Jan 10 13:46:49 CST 2020
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.productId
     *
     * @return the value of orderinfo.productId
     *
     * @mbggenerated Fri Jan 10 13:46:49 CST 2020
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.productId
     *
     * @param productid the value for orderinfo.productId
     *
     * @mbggenerated Fri Jan 10 13:46:49 CST 2020
     */
    public void setProductid(String productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.createDate
     *
     * @return the value of orderinfo.createDate
     *
     * @mbggenerated Fri Jan 10 13:46:49 CST 2020
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.createDate
     *
     * @param createdate the value for orderinfo.createDate
     *
     * @mbggenerated Fri Jan 10 13:46:49 CST 2020
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.status
     *
     * @return the value of orderinfo.status
     *
     * @mbggenerated Fri Jan 10 13:46:49 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.status
     *
     * @param status the value for orderinfo.status
     *
     * @mbggenerated Fri Jan 10 13:46:49 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}