#datasource配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 120000
  #redis相关配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
#eureka配置
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true #健康监测
#服务容器配置
server:
  undertow:
    io-threads: 16 #设置undertowIO线程数，它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程,不要设置过大，如果过大，启动项目会报错：打开文件数过多
    worker-threads: 200 #阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程,它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
    buffer-size: 1024 #以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理,每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    direct-buffers: true  #是否分配的直接内存(NIO直接分配的堆外内存